name: CI

on:
  push:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install composer
      run: composer install
      
    - uses: pipeline-components/php-codesniffer@v0.12.3
      with:
        directory: src/
    # ... then your own project steps ...
