name: CI

on:
  push:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install composer
      run: composer install
      
    - uses: php-actions/phpstan@v3
      with:
        php_version: 8.1
        path: src/
        configuration: ./phpstan.neon
        command: analyse
        
    # ... then your own project steps ...
