name: CI

on:
  push:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
      with:
        command: composer install --no-interaction --optimize-autoloader --classmap-authoritative
    - uses: php-actions/phpstan@v3
      with:
        path: src/
        configuration: ./phpstan.neon
        php_version: latest

    # ... then your own project steps ...
