name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpstan@v3
      with:
        path: src/
        configuration: ./phpstan.neon
        php_extensions: curl date exif fileinfo ftp gd hash iconv intl json libxml mbstring mysqli mysqlnd openssl PDO pdo_mysql Phar session SimpleXML sodium 

    # ... then your own project steps ...
