name: CI

on:
  push:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: Nyholm/roave-bc-check-docker@0.1.0
      with:
        path: src/
        configuration: phpstan.neon

    # ... then your own project steps ...
